name: CI

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          cache: npm
          node-version: lts/*
      - run: bun install
      - run: bun run type-check
      - run: bun run lint -- --max-warnings 0
